/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ren_JniNative */

#ifndef _Included_com_ren_JniNative
#define _Included_com_ren_JniNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ren_JniNative
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ren_JniNative_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_ren_JniNative
 * Method:    getJavaMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ren_JniNative_getJavaMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_ren_JniNative
 * Method:    getJavaStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ren_JniNative_getJavaStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_ren_JniNative
 * Method:    modifyJavaField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ren_JniNative_modifyJavaField
  (JNIEnv *, jobject);

/*
 * Class:     com_ren_JniNative
 * Method:    modifyJavaStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ren_JniNative_modifyJavaStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_ren_JniNative
 * Method:    callConstructorMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ren_JniNative_callConstructorMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_ren_JniNative
 * Method:    accessNonVirtualMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ren_JniNative_accessNonVirtualMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_ren_JniNative
 * Method:    toChineesString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ren_JniNative_toChineesString
  (JNIEnv *, jobject);

/*
 * Class:     com_ren_JniNative
 * Method:    sortArrayInC
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_ren_JniNative_sortArrayInC
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_ren_JniNative
 * Method:    getArrayFromC
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_ren_JniNative_getArrayFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_ren_JniNative
 * Method:    catchException
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ren_JniNative_catchException
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
